### ISSUE TITLE
Missing , in armsnippets.json

### ISSUE THREAD

**Issue by adouglas** [Azure/azure-xplat-arm-tooling#23]
Hi,

Line 1412 of armsnippets.json is missing a final comma meaning the file is not valid JSON.

https://github.com/Azure/azure-xplat-arm-tooling/blob/6b5012c73dc8399b3b660a5cb6b2b892d14a32f9/VSCode/armsnippets.json#L1412

**Comment by philon-msft** [comment]
Fixed - thanks @adouglas!
