### ISSUE TITLE
Nested Deployments can't have tags

### ISSUE THREAD

**Issue by ChrisLGardner** [Azure/azure-xplat-arm-tooling#33]
When trying to use the Nested Deployment snippet there are errors being thrown by Azure that you can't have Tags on this type of resource. This section needs to be removed, I'll put in a PR for this.

https://github.com/Azure/azure-xplat-arm-tooling/blob/2671455765a53eaa49425f04ed282a4670f6f62d/VSCode/armsnippets.json#L74

**Comment by kilasuit** [comment]
This was fixed by PR #34 so can be closed now

**Comment by philon-msft** [comment]
Thanks, @kilasuit!
